name: Publish rz-ui-vue To Npm

on:
  push:
    branches: [publish-rz-ui]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish npm'

    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 8.6.2
      - name: Install modules
        run: pnpm install
      - name: Build
        run: npm run build # cd packages/rz-ui-vue &&
      - name: 'Publish to the npm registry'
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.RZ_UI_TOKEN }}
      # - name: 'Publish to the npm registry'
      #   uses: primer/publish@3.0.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_AUTH_TOKEN: ${{ secrets.RZ_UI_TOKEN }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
      #   with:
      #     default_branch: 'publish'
      #     dir: './'
